# Generated by Django 3.0.6 on 2020-05-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
